version: 1.0.{build}

branches:
  only:
    - master

# Disable autmatic build and test
build: off
test: off

environment:
  global:
    platform: x64
    configuration: Release
    SHARED: OFF
  matrix:
    - platform: x86
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PYTHON: 'C:\Python27'
      SHARED: ON
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PYTHON: 'C:\Python36-x64'

install:
  - "set PATH=%PYTHON%;%PATH%"
  - ps: |
      if ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq "Visual Studio 2017") {
        $env:CMAKE_GENERATOR = "Visual Studio 15 2017"
      } else {
        $env:CMAKE_GENERATOR = "Visual Studio 14 2015"
      }
  - ps: if ($env:PLATFORM -eq "x64") { $env:CMAKE_GENERATOR += " Win64" }
  - "echo %APPVEYOR_BUILD_WORKER_IMAGE%-%PLATFORM% && cmake --version && python -V"
  - python -m ensurepip --upgrade && python -m pip install --upgrade pip wheel pytest numpy

build_script:
  - mkdir build
  - cd build && mkdir install
  - cmake -G "%CMAKE_GENERATOR%" -DBUILD_SHARED_LIBS:BOOL=%SHARED% -DCMAKE_INSTALL_PREFIX=install ..
  - cmake --build . --config %CONFIGURATION% --target ALL_BUILD

test_script:
  - ps: |
      if ($env:SHARED -eq "ON") {
        $env:PATH += ";$env:APPVEYOR_BUILD_FOLDER/build/bin/$env:CONFIGURATION"
      }
  - cd "bin/Test" && TestImage "../../../data/RGBD/color/00000.jpg" "../../../data/RGBD/depth/00000.png" && cd ../..
  - cd "bin/Test" && TestPoseGraph "../../../data/GraphOptimization/pose_graph_example_fragment.json" && cd ../..
  - cd "bin/Test" && TestProgramOptions --switch --int 123 --double 456.789 --string "Hello World" --vector "(0,0,1)" && cd ../..

after_test:
  - ps: |
      if ($env:SHARED -eq "ON") {
        7z a -tzip libraries.zip "bin/$env:CONFIGURATION/*.dll"
      }
  - 7z a -tzip libraries.zip lib\%CONFIGURATION%\*.lib
  - 7z a -tzip libraries.zip lib\%CONFIGURATION%\*.pyd
  #- python setup.py bdist_wheel

# cache:

artifacts:
  - path: 'build\libraries.zip'
    name: The Libraries

# deploy:
