# Copyright (c) 2018, Intel Labs
# Copyright (c) 2018, Open3D community
# Redistribution and use in full or partial is allowed according to the terms of the MIT license.

version: 1.0.{build}

branches:
  only:
    - master

notifications:
  - provider: Slack
    incoming_webhook:
      secure: HqR9gVr+989labqZvzVIzcVV1ZidvNs0X33nvzLUFRUDXw/BTdnpjCRaMZBQjZ669bE/QDeLEkV1A+O6jhCgnqQevyDAJipVC2zvgyO92dY=
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true

# Disable autmatic build and test
build: off
test: off

environment:
  upload_secret:
    secure: +eFp6HBoYdoCuh+9Tnc87Z6cZCrGX1jvH+XL6NRTh2I=
  platform: x64
  configuration: Release
  SHARED: OFF

  matrix:
    - platform: x86
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PYTHON: 'C:\Python27'
      SHARED: ON
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PYTHON: 'C:\Python36-x64'

install:
  - "set PATH=%PYTHON%;%PATH%"
  - ps: |
      if ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq "Visual Studio 2017") {
        $env:CMAKE_GENERATOR = "Visual Studio 15 2017"
      } else {
        $env:CMAKE_GENERATOR = "Visual Studio 14 2015"
      }
  - ps: if ($env:PLATFORM -eq "x64") { $env:CMAKE_GENERATOR += " Win64" }
  - "echo %APPVEYOR_BUILD_WORKER_IMAGE%-%PLATFORM% && cmake --version && python -V"
  - python -m ensurepip --upgrade && python -m pip install --upgrade pip wheel pytest numpy pypandoc

build_script:
  - mkdir build && cd build && mkdir install
  - cmake -G "%CMAKE_GENERATOR%" -DBUILD_SHARED_LIBS:BOOL=%SHARED% -DCMAKE_INSTALL_PREFIX=install ..
  - cmake --build . --config %CONFIGURATION% --target ALL_BUILD

test_script:
  - ps: |
      if ($env:SHARED -eq "ON") {
        $env:PATH += ";$env:APPVEYOR_BUILD_FOLDER/build/bin/$env:CONFIGURATION"
      }
  - cd "bin/Test" && TestProgramOptions --switch --int 123 --double 456.789 --string "Hello World" --vector "(0,0,1)" && cd ../..
  - cd "bin/Test" && TestImage "../../../data/RGBD/color/00000.jpg" "../../../data/RGBD/depth/00000.png" && cd ../..
# TODO: Not working with dynamic libs for some reason!
#  - cd "bin/Test" && TestPoseGraph "../../../data/GraphOptimization/pose_graph_example_fragment.json" && cd ../..

after_test:
  - cd ../util/package_generator && python setup.py --base-dir ../../build bdist_wheel && cd ../../build
  - ps: |
      Remove-item alias:curl
      Get-ChildItem ../util/package_generator/dist/*.whl |
        ForEach-Object {
          7z l $_
          curl -F "upload_secret=$env:upload_secret" -F "file=@$_" "http://deployment.open-3d.org/" 2> $null
        }

# cache:
